shell:
  - 'e2e/**'
  - 'wallet/build.sh'
  - 'demo.sh'
backend: &backend
  - 'wallet/**'
  - 'Cargo.toml'
  - 'Cargo.lock'
frontend:
  - 'wallet_ui/**'
  - '*.js'
  - '!(dfx).json'
canister: &canister
  - *backend
  - 'dfx.json'
e2e:
  - *canister
  - 'e2e/**'
demo:
  - *canister
  - 'demo.sh'
workflows:
  - '.github/**'
