name: build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      filter: ${{ steps.filter.outputs.demo == 'true' || steps.filter.outputs.workflows == 'true' }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: .github/filters.yml
  demo:
    needs: filter
    if: ${{ needs.filter.outputs.filter == 'true' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        rust: ['1.74.1']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust
        run: |
          rustup update ${{ matrix.rust }} --no-self-update
          rustup default ${{ matrix.rust }}
          rustup target add wasm32-unknown-unknown

      - name: Install dfx
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: "0.19.0"

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Demo
        run: sh demo.sh

  aggregate:
    name: demo:required
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [demo, filter]
    steps:
    - name: Check demo result
      if: ${{ needs.demo.result != 'success' && needs.filter.outputs.filter == 'true' }}
      run: exit 1
