name: build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust
        run: |
          rustup update 1.47.0 --no-self-update
          rustup default 1.47.0
          rustup target add wasm32-unknown-unknown

      - name: Install DFINITY SDK
        run: |
          DFX_VERSION=0.6.16
          pushd /tmp
          wget -q https://sdk.dfinity.org/install.sh
          yes Y | DFX_VERSION=$DFX_VERSION bash install.sh
          echo $HOME/bin >> $GITHUB_PATH
          rm install.sh
          popd

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 0.12

      - name: Demo
        run: sh demo.sh
