name: build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  demo:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust
        run: |
          rustup update 1.52.1 --no-self-update
          rustup default 1.52.1
          rustup target add wasm32-unknown-unknown

      - name: Install DFINITY SDK
        run: |
          DFX_VERSION=0.7.0-beta.4
          pushd /tmp
          wget -q https://sdk.dfinity.org/install.sh
          yes Y | DFX_VERSION=$DFX_VERSION bash install.sh
          echo $HOME/bin >> $GITHUB_PATH
          rm install.sh
          popd

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Demo
        run: sh demo.sh
