name: build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust
        run: |
          rustup update 1.47.0 --no-self-update
          rustup default 1.47.0

      - name: Install DFINITY SDK
        run: |
          DFX_VERSION=0.6.15
          pushd /tmp
          wget -q https://sdk.dfinity.org/install.sh
          yes Y | DFX_VERSION=$DFX_VERSION bash install.sh
          echo $HOME/bin >> $GITHUB_PATH
          rm install.sh
          popd

      - name: Install Node
        run: |
          pushd /tmp
          wget -O install-node.sh -q https://deb.nodesource.com/setup_12.x
          sudo bash install-node.sh
          sudo apt-get install -y nodejs
          popd

      - name: Demo
        run: sh demo.sh
