name: build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        rust: ["1.52.1"]
        # only dfx >= 0.8.3 lets us query multiple controllers
        dfx: ["0.8.4"]
    env:
      DFX_VERSION: ${{ matrix.dfx }}

    steps:
      - uses: actions/checkout@v1
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./wallet/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ matrix.rust }}-1
      - name: Install Rust
        run: |
          rustup update ${{ matrix.rust }} --no-self-update
          rustup default ${{ matrix.rust }}
          rustup target add wasm32-unknown-unknown
          rustup component add rustfmt
      - name: Provision Darwin
        if: matrix.os == 'macos-latest'
        run: bash .github/workflows/provision-darwin.sh
      - name: Provision Linux
        if: matrix.os == 'ubuntu-latest'
        run: bash .github/workflows/provision-linux.sh

      - name: Build
        run: |
          dfx start --background
          dfx canister create wallet
          dfx build wallet
          dfx stop

      - name: Run e2e tests vs dfx ${{ matrix.dfx }}
        run: |
          export DFX_WALLET_WASM=$GITHUB_WORKSPACE/wallet/target/wasm32-unknown-unknown/release/wallet-opt.wasm
          bats e2e/bash/*.bash
