name: Lint

on: [pull_request]

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      filter: ${{ steps.filter.outputs.backend == 'true' || steps.filter.outputs.workflows == 'true' }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: .github/filters.yml
  lint:
    name: Lint
    needs: filter
    if: ${{ needs.filter.outputs.filter == 'true' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: ['12.x']

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install dfx
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: "0.9.2"
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run Lint
        run: |
          dfx start --background
          dfx canister create wallet
          dfx build wallet
          cargo clippy --verbose --tests --benches -- -D clippy::all
        env:
          RUST_BACKTRACE: 1
  
  aggregate:
    name: lint:required
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [lint, filter]
    steps:
    - name: Check lint result
      if: ${{ needs.lint.result != 'success' && needs.filter.outputs.filter == 'true' }}
      run: exit 1
