name: shellcheck
on:
  pull_request:
    paths:
      - 'e2e/**'
      - '.github/**'
      - 'wallet/build.sh'
      - 'demo.sh'
  push:
    branches:
      - master

jobs:
  check:
    name: Check shell scripts
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install shellcheck
        run: |
          mkdir $HOME/bin
          cd $HOME/bin
          curl -L https://github.com/koalaman/shellcheck/releases/download/v0.7.1/shellcheck-v0.7.1.darwin.x86_64.tar.xz \
            | xz -d | tar x
      - name: Check e2e scripts
        run: $HOME/bin/shellcheck-v0.7.1/shellcheck e2e/bash/**/*.bash
      - name: Check provision scripts
        run: $HOME/bin/shellcheck-v0.7.1/shellcheck .github/workflows/*.sh
      - name: Check wallet build script
        run: $HOME/bin/shellcheck-v0.7.1/shellcheck wallet/build.sh
      - name: Check demo script
        run: $HOME/bin/shellcheck-v0.7.1/shellcheck demo.sh

  aggregate:
    name: check:required
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: check
    steps:
    - name: Check shellcheck result
      if: ${{ needs.check.result != 'success' }}
      run: exit 1