name: shellcheck
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      filter: ${{ steps.filter.outputs.shell }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: .github/filters.yml

  check:
    needs: filter
    if: ${{ needs.filter.outputs.filter == 'true' }}
    name: Check shell scripts
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install shellcheck
        run: |
          mkdir $HOME/bin
          cd $HOME/bin
          curl -L https://github.com/koalaman/shellcheck/releases/download/v0.7.1/shellcheck-v0.7.1.darwin.x86_64.tar.xz \
            | xz -d | tar x
      - name: Check e2e scripts
        run: $HOME/bin/shellcheck-v0.7.1/shellcheck e2e/bash/**/*.bash
      - name: Check provision scripts
        run: $HOME/bin/shellcheck-v0.7.1/shellcheck .github/workflows/*.sh
      - name: Check wallet build script
        run: $HOME/bin/shellcheck-v0.7.1/shellcheck wallet/build.sh
      - name: Check demo script
        run: $HOME/bin/shellcheck-v0.7.1/shellcheck demo.sh

  aggregate:
    name: shellcheck:required
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [check, filter]
    steps:
    - name: Check shellcheck result
      if: ${{ needs.check.result != 'success' && needs.filter.outputs.filter == 'true' }}
      run: exit 1