name: test
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      filter: ${{ steps.filter.outputs.backend == 'true' || steps.filter.outputs.workflows == 'true' }}
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
    - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
      id: filter
      with: 
        filters: .github/filters.yml
  test:
    name: Run built-in tests
    needs: filter
    if: ${{ needs.filter.outputs.filter == 'true' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: ['12.x']
    steps:
    - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
    - uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ./target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install dfx
      uses: dfinity/setup-dfx@e50c04f104ee4285ec010f10609483cf41e4d365 # main
      with:
        dfx-version: "0.9.2"
    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run tests
      run: |
        dfx start --background
        dfx canister create wallet
        dfx build wallet
        cargo test --verbose --no-fail-fast --workspace --all-targets --locked -- --nocapture
      env:
        RUST_BACKTRACE: 1

  aggregate:
    name: test:required
    needs: [test, filter]
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
    - name: Check test result
      if: ${{ needs.test.result != 'success' && needs.filter.outputs.filter == 'true' }}
      run: exit 1
